# \u73B0\u5728\u9ED8\u8BA4\u5C31\u662Fthymeleaf3 \u9ED8\u8BA4\u5C31\u662FHTML
#spring:
#  thymeleaf:
#    mode: HTML

spring:
  profiles:
    active: dev

  messages:
    # 默认是messages 所以文件名要叫messages
    basename: i18n/messages
    
comment.avatar: /images/avatar.jpg